name: qrbased_frontend
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.40.0
  cupertino_icons: ^1.0.2
  provider: ^6.1.1 # for State management
  mobile_scanner: ^2.1.0
  qr_scanner_overlay: ^0.0.2
  qr_flutter: ^4.1.0
  http: ^1.1.0
  shared_preferences: ^2.2.3
  get: ^4.6.6
  dio: ^5.4.3+1
  image: ^4.2.0
  path_provider: ^2.1.3
  file_picker: ^8.0.0+1
  permission_handler: ^11.0.1
  intl: ^0.19.0
  qr_code_scanner: ^1.0.1
  carousel_slider: ^4.2.1
  socket_io_client: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_lints: ^2.0.0
  bcrypt: ^1.1.3
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+4

flutter:
  assets:
    - assets/data/small_logo.png
    - assets/data/logo.png
    - assets/data/izepay_logo2.png
    - assets/data/profile_picture.jpg
    - assets/izelogo.png
    - assets/profile_picture.jpg
    - assets/data/recipient_image.jpg
    - assets/slide1.jpg
    - assets/slide2.jpg
    - assets/slide3.png

  uses-material-design: true

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
